-- AlterTable
ALTER TABLE "Campaign"
ADD COLUMN "channel" TEXT NOT NULL DEFAULT '',
ADD COLUMN "budget" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "start_date" TIMESTAMP(3) NOT NULL DEFAULT now();

ALTER TABLE "Campaign"
ALTER COLUMN "channel" DROP DEFAULT,
ALTER COLUMN "budget" DROP DEFAULT,
ALTER COLUMN "start_date" DROP DEFAULT;
